# Generated by Django 2.1.7 on 2019-12-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_file',
            field=models.FileField(default='jammin/media', upload_to=''),
        ),
    ]
