# Generated by Django 3.0 on 2019-12-09 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='published',
        ),
        migrations.AddField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 16, 55, 23, 427884, tzinfo=utc)),
        ),
    ]
