# Generated by Django 3.0 on 2019-12-09 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0002_auto_20191209_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 17, 0, 43, 338865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='dl_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
