# Generated by Django 3.0 on 2019-12-09 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0005_auto_20191209_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 17, 8, 2, 24034, tzinfo=utc)),
        ),
    ]
