# Generated by Django 3.0 on 2019-12-09 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0014_auto_20191209_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='dl_count',
        ),
        migrations.AlterField(
            model_name='downloads',
            name='mid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 2, 33, 921380, tzinfo=utc)),
        ),
    ]
