# Generated by Django 3.0 on 2019-12-09 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0015_auto_20191209_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 2, 37, 978489, tzinfo=utc)),
        ),
    ]
