# Generated by Django 3.0 on 2019-12-09 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0016_auto_20191209_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Musicians',
        ),
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 3, 2, 50343, tzinfo=utc)),
        ),
    ]
