# Generated by Django 3.0 on 2019-12-09 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0019_auto_20191209_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='dl_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 6, 47, 652371, tzinfo=utc)),
        ),
    ]
