# Generated by Django 3.0 on 2019-12-09 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0020_auto_20191209_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 8, 22, 111147, tzinfo=utc)),
        ),
    ]
