# Generated by Django 3.0 on 2019-12-09 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jammin', '0021_auto_20191209_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 19, 14, 15, 975508, tzinfo=utc)),
        ),
    ]
